name: Tests master

on:
  push:
    branches:
      - main

jobs:
  date:
    if: !contains(github.event.head_commit.message, 'skip ci')  && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'pykeen/gha-together')
    name: Date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print the date
        run: date
